"""remove body from todos

Revision ID: aa484b556ca7
Revises: 5ba845aa4324
Create Date: 2023-05-04 01:39:46.321117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa484b556ca7'
down_revision = '5ba845aa4324'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_column('body')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
